logging:
  level:
    com.fastcampus.pass: debug
    org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:                           # docker-compose에 정의했던 DB 접속 정보입니다.
    url: ${MYSQL_DOCKER_URL}
    username: ${MYSQL_DOCKER_USERNAME}
    password: ${MYSQL_DOCKER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:                             # Spring Boot2부터 default DBCP는 hikariCP입니다.
      maximum-pool-size: 20             # pool에 보관 가능한 최대 connection 수
      # minimum-idle: 20
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.WeblogicJtaPlatform
  sql.init.mode: always
  batch:
    jdbc:
      initialize-schema: always
